sponsorship:
  - nick: f***n
    money: 6.66
    desc: ä¸­è€ƒåŠ æ²¹ï¼
  - nick: ä»™ç«¥åŠå¯¼ä½“
    money: 20.00
    desc: å°å¼ŸåŠ æ²¹
  - nick: "**ç©"
    money: 2.00
  - nick: "**B"
    money: 2.00
    desc: æ„Ÿè°¢
  - nick: "**ç‡š"
    money: 5.00
  - nick: "**å¸…"
    money: 3.00
  - nick: "**å‹‡"
    money: 3.00
  - nick: "**èˆª"
    money: 1.00
  - nick: "ğŸã€‚"
    money: 1.00
    desc: å¤ªå‰å®³å•¦
  - nick: é‡‘é™µç¬‘ç¬‘ç”Ÿ
    money: 6.66
    desc: æ„Ÿè°¢ï¼ï¼ï¼
  - nick: "å”¯ä¸€."
    money: 3.00
  - nick: æ§æ ¹æ¢¦è§‰_
    money: 6.66
  - nick: "-"
    money: 3.00
  - nick: å¤±å»æ¢¦æƒ³çš„è™¾çƒå›
    money: 1.00
  - nick: "å·¦ç„¶æ˜¯èŒç¥å§(â¸â¸Ã¬ _ Ã­â¸â¸ï¼‰"
    money: 1.00
  - nick: "**é”"
    money: 20.00
  - nick: "**å½¦"
    money: 1.55
    desc: æ„Ÿè°¢æœ‰ä½ ã€‚
  - nick: "**æ ‹"
    money: 0.50
  - nick: "*é˜³"
    money: 1.00
  - nick: "**å¨´"
    money: 3.00
  - nick: "D*a"
    money: 2.00
  - nick: "*ä¸š"
    money: 5.00
  - nick: "t*w"
    money: 1.00
  - nick: "D*s"
    money: 5.00
  - nick: "*~"
    money: 1.00
  - nick: "*äº‹"
    money: 5.20
    desc: æ„Ÿè°¢ä½ çš„å–œèŒ¶å°ç¨‹åºï¼Œå¾ˆå¥½ç”¨ï¼Œè°¢è°¢ï¼Œè¿™æ˜¯ä¸€ç‚¹å°å¿ƒæ„
  - nick: "@*^"
    money: 1.00
  - nick: "*ğŸ‹"
    money: 1.00
  - nick: "*åœ¨"
    money: 1.00
  - nick: "*å®"
    money: 5.00
    desc: è°¢è°¢åˆ†äº«å–œèŒ¶æ¯è´´å¹³å°
  - nick: "***"
    money: 3.00
  - nick: "*Y"
    money: 5.20
    desc: è¶…çº§æ£’ï¼
  - nick: "è±†*."
    money: 1.88
  - nick: "L*i"
    money: 1.00
    desc: è°¢è°¢ä½ åšçš„å–œèŒ¶ç½‘å€ çœŸçš„å¾ˆæ–¹ä¾¿
  - nick: "*0"
    money: 6.66
    desc: çœŸçš„éå¸¸å¥½å•Šï¼è¶…çº§æ–¹ä¾¿ï¼æ„Ÿè°¢è€å¸ˆï¼
  - nick: "*é±¼"
    money: 10.00
    desc: è°¢è°¢å¤§äººå¼€å‘
  - nick: "C*e"
    money: 5.00
    desc: å–œå¸–è½¯ä»¶å¥½ä½¿ï¼æ„Ÿè°¢ï¼ˆ*ï¼¾ãƒ¯ï¼¾*ï¼‰
  - nick: "ç»*6"
    money: 10.00

project:
  - name: Monet-All
    url: https://monet.jerryz.com.cn/
    desc: Androidè«å¥ˆå–è‰²æ•´åˆMagiskæ¨¡å—
  - name: Luogu-User-Card
    url: https://api.jerryz.com.cn/
    desc: æ´›è°·ç”¨æˆ·ä¿¡æ¯å¡ç‰‡
  - name: Cards
    url: https://cards.jerryz.com.cn/
    desc: ä¸ªäººèº«ä»½å¡ç‰‡ API åŠç”Ÿæˆå™¨
  - name: Links
    url: https://links.jerryz.com.cn/
    desc: å‹é“¾åˆé›†
  - name: HTML-editor
    url: https://html.jerryz.com.cn/
    desc: HTMLä»£ç åœ¨çº¿ç¼–è¾‘å™¨
  - name: JZHome
    url: https://jerryz.com.cn/
    desc: Jerry Zhouçš„ä¸ªäººä¸»é¡µ
  - name: Game
    url: /game
    desc: è§£å‹å°æ¸¸æˆ

account:
  - name: å¾®ä¿¡
    id: jerryz0506
  - name: QQ
    id: 2098412009
  - name: GitHub
    id: YangguangZhou
  - name: æ´›è°·
    id: 253620
  - name: é…·å®‰
    id: "@JerryZhouYG"
  - name: Bilibili
    id: "@Jerry_ZhouYG"
  - name: Twitter
    id: "@JerryZhouYG"
  - name: Telegram
    id: "@jerryzyg"

friend:
  - nick: Jerry Zhou
    url: https:/jerryz.com.cn
    desc: æ°¸è¿œç›¸ä¿¡ç¾å¥½çš„äº‹æƒ…å³å°†å‘ç”Ÿ

timeline:
  - year: 2018
    meta: [
        { date: "ä¸ŠåŠå¹´",               desc: "é¦–æ¬¡æ¥è§¦å›¾å½¢åŒ–ç¼–ç¨‹" },
        { date: "7 æœˆ",                 desc: "é¦–æ¬¡æ¥è§¦Javascript" },
        { date: "7 æœˆ",                 desc: "å†™ä¸‹äº†ç¬¬ä¸€ä¸ªâ€œHello, World!â€" },
        { date: "7 æœˆ",                 desc: "ç³»ç»Ÿåœ°å­¦ä¹ Javascript" },
        { date: "8 æœˆ",                 desc: "å†™ä¸‹ç¬¬ä¸€ä¸ªè‡ªå·±åˆ›ä½œçš„å°ç¨‹åºï¼šçŒœä¸€çŒœ" },
    ]
  - year: 2019
    meta: [
        { date: "ä¸ŠåŠå¹´",               desc: "é¦–æ¬¡æ¥è§¦Cè¯­è¨€" },
        { date: "2 æœˆ",                 desc: "å‰å¾€åŠ æ‹¿å¤§ï¼Œå¼€å¯äº†ä¸ºæœŸåŠå¹´çš„ç•™å­¦" },
        { date: "8 æœˆ 30 æ—¥",           desc: "é¦–æ¬¡æ¥è§¦C++" },
        { date: "8 æœˆ 30 æ—¥",           desc: "æ³¨å†Œäº†OpenJudgeè´¦å·" },
        { date: "8 æœˆ 30 æ—¥",           desc: "ACäº†è¶…çº§ç›ä¸½" },
        { date: "9 æœˆ 6 æ—¥",            desc: "æ³¨å†Œäº†æ´›è°·è´¦å·" },
        { date: "9 æœˆ",                 desc: "å¼€å§‹ç³»ç»Ÿåœ°å­¦ä¹ C++" },
        { date: "10 æœˆ",                desc: "å‚åŠ CSP-Jï¼Œä¸å‡ºæ„å¤–åœ°çˆ†é›¶äº†ï¼ˆå¿˜è®°æ€ä¹ˆå†™freopenï¼‰" },
        { date: "11 æœˆ",                desc: "é¦–æ¬¡æ¥è§¦Python" },
    ]
  - year: 2020
    meta: [
        { date: "6 æœˆ",                 desc: "é€šè¿‡æ‘‡å·è¿›å…¥äº†æ¢¦å¯ä»¥æ±‚çš„äº‘å¤§é™„ä¸­" },
        { date: "7 æœˆ",                 desc: "å¼€å§‹å­¦ä¹ éƒ¨åˆ†ç®€å•çš„ç®—æ³•" },
        { date: "10 æœˆ",                desc: "å‚åŠ CSP-Jï¼Œæ°´äº†ä¸ª100åˆ†ï¼Œå–œæçœä¸€" },
        { date: "10 æœˆ",                desc: "å‚åŠ CSP-Sï¼Œçˆ†é›¶äº†" },
        { date: "11 æœˆ",                desc: "æ´›è°·ç»¿å+ç»¿æ ‡" },
    ]
  - year: 2021
    meta: [
        { date: "9 æœˆ",                 desc: "å¼€å§‹è¿›ä¸€æ­¥åœ°å­¦ä¹ C++ç®—æ³•ï¼Œå–å¾—äº†ä¸å°çš„è¿›æ­¥" },
        { date: "10 æœˆ",                desc: "å‚åŠ CSP-Jï¼Œ101åˆ†" },
        { date: "10 æœˆ",                desc: "å‚åŠ CSP-Sï¼Œ15åˆ†" },
        { date: "10 æœˆ",                desc: "å‚åŠ NOIPï¼Œ60åˆ†ï¼Œå·®5åˆ†ä¸€ç­‰å¥–" },
        { date: "11 æœˆ",                desc: "å¼€å§‹æ­å»ºLuogu-User-Card" },
        { date: "11 æœˆ",                desc: "å¼€å§‹æ­å»ºä¸ªäººåšå®¢å’Œä¸ªäººä¸»é¡µ" },
    ]
  - year: 2022
    meta: [
        { date: "1 æœˆ",                 desc: "å¼€å§‹æ­å»ºCards" },
        { date: "3 æœˆ",                 desc: "å‚åŠ è”åˆçœé€‰ï¼Œ40åˆ†" },
        { date: "4 æœˆ",                 desc: "è¿›å…¥çœé˜Ÿï¼Œä½†æœ€ç»ˆæ”¾å¼ƒäº†å‚åŠ NOIçš„æœºä¼š" },
        { date: "5 æœˆ",                 desc: "å‚åŠ THUSC" },
        { date: "6 æœˆ 18 æ—¥",           desc: "é¡ºåˆ©é€šè¿‡å°ä¸‰ç§‘ä¸­è€ƒ" },
        { date: "9 æœˆ",                 desc: "åˆ¶ä½œäº†Monet-Allï¼Œä¸Šäº†é…·å®‰å¤´æ¡" },
        { date: "10 æœˆ",                desc: "å‚åŠ CSP-Sï¼Œ25åˆ†ï¼Œå·®5åˆ†å°±èƒ½æ‹¿å¥–" },
    ]
  - year: 2023
    meta: [
        { date: "1 æœˆ 1 æ—¥",            desc: "ä»Šå¹´æ˜¯ä¸­è€ƒå¹´" },
        { date: "2 æœˆ",                 desc: "å¼€å§‹æ­å»ºLinks" },
        { date: "2 æœˆ",                 desc: "å¤§å¹…æ›´æ–°Monet-All" },
        { date: "3 æœˆ",                 desc: "å‚åŠ CCFæ˜¥æµ‹ï¼Œ180åˆ†ï¼Œåˆšå¥½åˆ°ä¸€ç­‰å¥–çº¿" },
        { date: "3 æœˆ 18 æ—¥",           desc: "å¤§å¹…åº¦åœ°æ›´æ–°ä¸ªäººä¸»é¡µ" },
        { date: "3 æœˆ - 6 æœˆ",           desc: "å…¨åŠ›å¤‡æˆ˜ä¸­è€ƒ" },
        { date: "6 æœˆ 16 æ—¥ - 6 æœˆ 18 æ—¥", desc: "ä¸­è€ƒ" },
        { date: "7 æœˆ",                 desc: "ä¸­è€ƒå–å¾—äº†ä¸é”™çš„æˆç»©" },
        { date: "7 æœˆ",                 desc: "è€ƒä¸Šäº†å¿ƒä»ªçš„é«˜ä¸­ï¼šYNSDFZ" },
    ]
